[phases.setup]
nixPkgs = ['nodejs_18', 'python310']

[phases.install]
dependsOn = ['setup']
cmds = [
  'pip install -r requirements.txt',
  'cd frontend && npm install'
]

[phases.build]
dependsOn = ['install']
cmds = [
  'cd frontend && npm run build',
  'cp -r frontend/build/* .',
  'rm -rf frontend/build'
]

[start]
cmd = 'gunicorn app:app' 