[phases.setup]
nixPkgs = ["gcc", "python311"]

[phases.install]
cmds = ["pip install --upgrade pip setuptools wheel"]

[phases.build]
cmds = ["pip install -r requirements.txt"]

# Commented out since we're using Dockerfile
# [start]
# cmd = "python app.py" 