[phases.setup]
nixPkgs = ['python310', 'python310Packages.pip', 'python310Packages.virtualenv', 'nodejs_18']

[phases.install]
cmds = [
  'python3 -m venv venv',
  'source venv/bin/activate && pip install -r requirements.txt',
  'cd frontend && npm install --legacy-peer-deps'
]

[phases.build]
cmds = [
  'cd frontend && CI=false npm run build',
  'cp -r frontend/build/* .',
  'rm -rf frontend/build'
]

[start]
cmd = 'source venv/bin/activate && python -m gunicorn app:app --bind 0.0.0.0:$PORT' 