[phases.setup]
nixPkgs = ['python310', 'nodejs_18']

[phases.install]
cmds = [
  'pip install -r requirements.txt',
  'cd frontend && npm install --legacy-peer-deps'
]

[phases.build]
cmds = [
  'cd frontend && CI=false npm run build',
  'cp -r frontend/build/* .',
  'rm -rf frontend/build'
]

[start]
cmd = 'python -m gunicorn app:app --bind 0.0.0.0:$PORT' 