[build]
builder = "nixpacks"
buildCommand = "cd frontend && npm install && npm run build && cd .. && cp -r frontend/build/* . && rm -rf frontend/build"

[deploy]
startCommand = "gunicorn app:app"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10 